'------------------------------------------------------------------------------
' <auto-generated>
'     這段程式碼是由工具產生的。
'     執行階段版本:2.0.50727.4927
'
'     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
'     變更將會遺失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''HSM_Delay 類別。
'''</summary>
'''<remarks>
'''自動產生的類別。
'''</remarks>
Partial Public Class HSM_Delay

    '''<summary>
    '''form1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ph 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents ph As Global.hPMISWEB.PageHeader

    '''<summary>
    '''gvDaily 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents gvDaily As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''Panel1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''gvMonth 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents gvMonth As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnUp 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents btnUp As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnDown 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents btnDown As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMonth 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents lblMonth As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDA 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents lblDA As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDR 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents lblDR As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDS 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents lblDS As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDO 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents lblDO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotal 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hDA1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDA1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hDR1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDR1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hDS1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDS1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hDO1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDO1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hTotal1 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hTotal1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hDA2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDA2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hDR2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDR2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hDS2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDS2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hDO2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDO2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hTotal2 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hTotal2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hDate 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hStartDate 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hStartDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hEndDate 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hEndDate As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hAnc 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents hAnc As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''DAAct 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DAAct As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''DRAct 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DRAct As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''DSAct 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DSAct As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''DOAct 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents DOAct As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''TotalAct 控制項。
    '''</summary>
    '''<remarks>
    '''自動產生的欄位。
    '''若要修改，請將欄位宣告從設計工具檔案移到程式碼後置檔案。
    '''</remarks>
    Protected WithEvents TotalAct As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
