'------------------------------------------------------------------------------
' <auto-generated>
'     此程式碼由工具產生。
'     若要新增或移除成員，請在設計工具檔案中進行變更。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class HBM_Production

    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    Protected WithEvents ph As Global.hPMISWEB.PageHeader

    Protected WithEvents LabelStartdate As Global.System.Web.UI.WebControls.Label

    Protected WithEvents LabelEnddate As Global.System.Web.UI.WebControls.Label

    Protected WithEvents gvMonth1 As Global.System.Web.UI.WebControls.GridView

    Protected WithEvents lblMonth1 As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblHxx As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblFxx As Global.System.Web.UI.WebControls.Label

    Protected WithEvents lblLxx As Global.System.Web.UI.WebControls.Label

End Class
